spring:
  main:
    banner-mode: off
  datasource:
    url: ${url}?createDatabaseIfNotExist=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${user}
    password: ${password}
  jpa:
    defer-datasource-initialization: false
    open-in-view: false
    properties:
      hibernate:
        type: uuid-char
        ddl-auto: update
        dialect: org.hibernate.dialect.MySQLDialect
  liquibase:
    change-log: db/changeLog/changes/changelog-master.xml
    drop-first: true
server:
  port: 8080